# Generated by Django 2.1.3 on 2019-01-18 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
