# Generated by Django 2.1.3 on 2018-12-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rent_or_sale',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('To Rent', 'To Rent')], default='For Sale', max_length=100),
        ),
    ]
