# Generated by Django 2.1.3 on 2018-11-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='state',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='zipcode',
            new_name='postcode',
        ),
    ]
