# Generated by Django 2.1.3 on 2018-11-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20181122_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='garages',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
