# Generated by Django 2.1.3 on 2018-12-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_rent_or_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='rent_or_sale',
            new_name='for_sale_or_to_rent',
        ),
    ]
