# Generated by Django 2.1.3 on 2018-12-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20181201_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='for_sale_or_to_rent',
            new_name='for_sale_or_rent',
        ),
    ]
