# Generated by Django 2.1.3 on 2018-11-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_garages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='garages',
        ),
        migrations.AddField(
            model_name='listing',
            name='garage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='sqft',
            field=models.IntegerField(default=0),
        ),
    ]
