# Generated by Django 2.1.3 on 2019-01-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='position',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
