bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5,
  '6':6,
  '7':7,
  '8':8,
  '9':9,
  '10':10
  }

price_choices = {
  '100000':'£100,000',
  '200000':'£200,000',
  '300000':'£300,000',
  '400000':'£400,000',
  '500000':'£500,000',
  '600000':'£600,000',
  '700000':'£700,000',
  '800000':'£800,000',
  '900000':'£900,000',
  '1000000':'£1M+',
}

county_choices = (
    ('Bedfordshire', 'Bedfordshire'),
    ('Berkshire', 'Berkshire'),
    ('Bristol', 'Bristol'),
    ('Buckinghamshire', 'Buckinghamshire'),
    ('Cambridgeshire', 'Cambridgeshire'),
    ('Cheshire', 'Cheshire'),
    ('City of London', 'City of London'),
    ('Cornwall', 'Cornwall'),
    ('Cumbria', 'Cumbria'),
    ('Derbyshire', 'Derbyshire'),
    ('Devon', 'Devon'),
    ('Dorset', 'Dorset'),
    ('County Durham', 'County Durham'),
    ('East_Riding_of_Yorkshire', 'East Riding of Yorkshire'),
    ('East_Sussex', 'East Sussex'),
    ('Essex', 'Essex'),
    ('Gloucestershire', 'Gloucestershire'),
    ('Greater_London', 'Greater London'),
    ('Greater_Manchester', 'Greater Manchester'),
    ('Hampshire', 'Hampshire'),
    ('Herefordshire', 'Herefordshire'),
    ('Hertfordshire', 'Hertfordshire'),
    ('Isle_of_Wight', 'Isle of Wight'),
    ('Kent', 'Kent'),
    ('Lancashire', 'Lancashire'),
    ('Leicestershire', 'Leicestershire'),
    ('Lincolnshire', 'Lincolnshire'),
    ('Merseyside', 'Merseyside'),
    ('Norfolk', 'Norfolk'),
    ('North_Yorkshire', 'North Yorkshire'),
    ('Northamptonshire', 'Northamptonshire'),
    ('Northumberland', 'Northumberland'),
    ('Nottinghamshire', 'Nottinghamshire'),
    ('Oxfordshire', 'Oxfordshire'),
    ('Rutland', 'Rutland'),
    ('Shropshire', 'Shropshire'),
    ('Somerset', 'Somerset'),
    ('South_Yorkshire', 'South Yorkshire'),
    ('Staffordshire', 'Staffordshire'),
    ('Suffolk', 'Suffolk'),
    ('Surrey', 'Surrey'),
    ('Tyne_and_Wear', 'Tyne and Wear'),
    ('Warwickshire', 'Warwickshire'),
    ('West_Midlands', 'West Midlands'),
    ('West_Sussex', 'West Sussex'),
    ('West_Yorkshire', 'West Yorkshire'),
    ('Wiltshire', 'Wiltshire'),
    ('Worcestershire', 'Worcestershire')
)